{{- if .Values.imsApi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ims.imsApiName" . }}
  labels:
    {{- include "ims.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.imsApi.replicaCount }}
  selector:
    matchLabels:
      {{- include "ims.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ims-api
  template:
    metadata:
      labels:
        {{- include "ims.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ims-api
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      containers:
        - name: ims-api
          image: "{{ .Values.imsApi.image.repository }}:{{ .Values.imsApi.image.tag }}"
          imagePullPolicy: {{ .Values.imsApi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.imsApi.containerPort | default .Values.imsApi.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "ims.configMapName" . }}
            - secretRef:
                name: {{ .Values.secretRefs.existingSecretName }}
          resources:
{{ toYaml .Values.imsApi.resources | nindent 12 }}
          env:
            - name: PORT
              value: {{ .Values.imsApi.env.PORT | quote }}

            - name: AUTH_DISABLED
              value: {{ .Values.imsApi.env.AUTH_DISABLED | quote }}

            - name: PGBOUNCER_HOST
              value: {{ .Values.imsApi.env.PGBOUNCER_HOST | quote }}

            - name: PGBOUNCER_PORT
              value: {{ .Values.imsApi.env.PGBOUNCER_PORT | quote }}

            - name: POSTGRES_DB
              value: {{ .Values.imsApi.env.POSTGRES_DB | quote }}

            - name: POSTGRES_USER
              value: {{ .Values.imsApi.env.POSTGRES_USER | quote }}

            - name: POSTGRES_PASSWORD
              value: {{ .Values.imsApi.env.POSTGRES_PASSWORD | quote }}

            - name: REDIS_HOST
              value: {{ printf "%s-redis" .Release.Name | quote }}

            - name: REDIS_PORT
              value: {{ .Values.imsApi.env.REDIS_PORT | quote }}

            - name: SESSION_KEY_PREFIX
              value: {{ .Values.imsApi.env.SESSION_KEY_PREFIX | quote }}
          livenessProbe:
            httpGet:
              path: {{ .Values.imsApi.probes.liveness.path | quote }}
              port: http
            initialDelaySeconds: {{ .Values.imsApi.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.imsApi.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.imsApi.probes.readiness.path | quote }}
              port: http
            initialDelaySeconds: {{ .Values.imsApi.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.imsApi.probes.readiness.periodSeconds }}
{{- end }}