{{- if .Values.workerApi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ims.workerApiName" . }}
  labels:
    {{- include "ims.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.workerApi.replicaCount }}
  selector:
    matchLabels:
      {{- include "ims.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker-api
  template:
    metadata:
      labels:
        {{- include "ims.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker-api
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      containers:
        - name: worker-api
          image: "{{ .Values.workerApi.image.repository }}:{{ .Values.workerApi.image.tag }}"
          imagePullPolicy: {{ .Values.workerApi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.workerApi.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ include "ims.configMapName" . }}
            - secretRef:
                name: {{ .Values.secretRefs.existingSecretName }}
          resources:
{{ toYaml .Values.workerApi.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.workerApi.probes.liveness.path | quote }}
              port: http
            initialDelaySeconds: {{ .Values.workerApi.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.workerApi.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.workerApi.probes.readiness.path | quote }}
              port: http
            initialDelaySeconds: {{ .Values.workerApi.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.workerApi.probes.readiness.periodSeconds }}
{{- end }}