replicaCount: 2

image:
  repository: joforrester/general-api
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 3000

ingress:
  enabled: true
  className: nginx
  path: /
  pathType: Prefix
  annotations: {}


env:
  NODE_ENV: production
  DB_HOST: "173.249.8.56"
  DB_PORT: "5432"
  DB_USER: "ims-user"
  DB_NAME: "ims-user"
  REDIS_HOST: "redis-master.ims.svc.cluster.local"
  REDIS_PORT: "6379"
  KAFKA_BROKERS: "YOUR_EXTERNAL_KAFKA:9092"

secretEnv:
  DB_PASSWORD: "29WK3n4fn43!!m3HH3d"
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60

serviceAccount:
  name: tenant-xyz-app

containerPort: 3000  # keep aligned with your app; defaulting to service.port also works

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /readyz
    initialDelaySeconds: 10
    periodSeconds: 5

