apiVersion: v1
kind: Secret
metadata:
  name: ims-provisioner-secret
  namespace: ims-system
type: Opaque
stringData:
  ADMIN_API_KEY: "ims-key"
  DBHOST: "173.249.8.56"
  DBPORT: "5432"
  DBUSER: "test-user"
  DBPASSWORD: "password"
              

  