apiVersion: v1
kind: Service
metadata:
  name: ims-provisioner
  namespace: ims-system
  labels:
    app: ims-provisioner
spec:
  type: ClusterIP
  selector:
    app: ims-provisioner
  ports:
    - name: http
      port: 80
      targetPort: http