spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "ims-api.fullname" . }}
                port:
                  number: 3000
