apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ims-on-demand
  namespace: warehouse-tenant-xyz
  labels:
    app: ims-on-demand
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "10"        # target concurrent requests per pod
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "20"
    spec:
      serviceAccountName: tenant-xyz-app
      containers:
        - image: your-docker-user/ims-on-demand:latest
          envFrom:
            - configMapRef:
                name: ims-config
            - secretRef:
                name: ims-db-secret
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
