apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ims-api-hpa
  namespace: warehouse-tenant-xyz
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ims-api
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    # Example of custom metrics; depends on Prometheus adapter setup
    # - type: Pods
    #   pods:
    #     metric:
    #       name: http_requests_per_second
    #     target:
    #       type: AverageValue
    #       averageValue: "20"
